# Opções de patrocínio e doação

# Descomente quando tiver conta configurada:
# github: milenemolina
# patreon: seu-usuario
# ko_fi: seu-usuario

custom: ["https://wa.me/5567992057963?text=Ol%C3%A1%2C%20quero%20comprar%20o%20m%C3%B3dulo%20IA"]
